# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant
  vm_hostname: oracle.myorg.chefdemo.net
  #gui: true
  # Mount local /Users/apop/chef-kits folder as /mnt/share on the VM
  synced_folders:
  - ['~/chef-kits', '/mnt/share', 'disabled: false']
  customize:
    cpus: 2
    memory: 2048
    name: oracle.myorg.chefdemo.net

driver_config:
  # I don't login often, but when I do, I do it as root
  username: root
  password: vagrant

provisioner:
  name: chef_zero
    chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  # To get above line to work, one time config of Vagrantfile as below
  # on your local workstation ( ie where yeu run kitchen commands )
  # also need this in your local Vagrantfile config
  # ~/.vagrant.d/Vagrantfile
  # Vagrant.configure("2") do |config|
  #   if Vagrant.has_plugin?("vagrant-cachier")
  #     config.cache.scope = :box
  #     config.cache.enable :chef
  #     config.cache.enable :gem
  #     config.cache.enable :apt
  #     config.cache.enable :yum
  #   end
  # end

  # Install this exact version of chef-client
  #require_chef_omnibus: 12.4.1
  # Use the local chef-client rpm specified in install_chef_rpm.sh:
  #chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes
    audit_mode: :disabled

platforms:
  - name: centos-72
    driver:
      box: 'chef/centos-7.2'
      # see available box urls here: https://opscode-vm-bento.s3.amazonaws.com/
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box
      #box_url: file:///Users/srussell/Source//Pushjobs/opscode_centos-6.6_chef-provisionerless.box
      # Use the default host-only network along the NAT one. Makes life easier from a networking perspective
      network:
      - ['private_network', {ip: '192.168.56.82'}]

suites:
  - name: default
    run_list:
      - recipe[oracle_deleteattributes::default]
