name 'oracle_deleteattributes'
maintainer 'Scott Russell'
maintainer_email 'srussell@chef.io'
license 'all_rights'
description 'Deletes a note addribute depending on whether a templates was used'
long_description 'Deletes a note addribute depending on whether a templates was used'
version '0.1.0'
